### ISSUE TITLE
Scrolling the cms licences view is broken

### ISSUE THREAD

**Issue by janhenckens** [pixelandtonic/craftnet#120] opened 2019-01-17 08:15 UTC
On https://id.craftcms.com/licenses/cms vertical scrolling is broken, making the any item below the fold unreachable.

**Comment by angrybrad** [comment] 2019-01-17 17:57
@janhenckens i'm not able to reproduce that locally on the latest Chrome. What browser/version/OS are you using?

**Comment by janhenckens** [comment] 2019-01-17 18:16
Should have added that, sorry! I'm on the latest Firefox (64.0.2) on Mac OS Mojave.

**Comment by angrybrad** [comment] 2019-01-17 18:37
@janhenckens ahh, i can reproduce there. thanks!

**Comment by angrybrad** [comment] 2019-01-21 19:12
Fixed in https://github.com/pixelandtonic/craftnet/commit/d2c8475c28cacdf2596eaf99816b398cae4158ac

**Closed by angrybrad** 2019-01-21 19:12 UTC
Labels: bug
